{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: olfactory-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: olfactory-fragrance-backend
                port:
                  number: 80
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - path: /()(.*)
          pathType: Prefix
          backend:
            service:
              name: olfactory-frontend
              port:
                number: 80
        - path: /api(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: olfactory-fragrance-backend
              port:
                number: 80
{{- end }}